voxel51/fiftyone-plugins

README.md
plugins/indexes/README.md
plugins/indexes/__init__.py
plugins/indexes/fiftyone.yml

Adds a plugin for managing database indexes!
Specifically, a `manage_indexes` operator is included that supports:
- Viewing all existing indexes
- Creating indexes for any valid unindexed field
- For video datasets, frame fields are included
- For grouped datasets, compound indexes `[(group.name, 1), (path, 1)]` are also created 
- Deleting any (non-default) existing indexes
```py
session = fo.launch_app()
session.dataset = foz.load_zoo_dataset("quickstart")
session.dataset = foz.load_zoo_dataset("quickstart-video")
session.dataset = foz.load_zoo_dataset("quickstart-groups")
```
https://github.com/voxel51/fiftyone-plugins/assets/25985824/9e36d070-04e8-4b34-9ab4-71adc4781b32
https://github.com/voxel51/fiftyone-plugins/assets/25985824/2edb853c …

Indexes plugin

---

README.md

A plugin to filter on two numeric ranges simultaneously

Adding double band filter plugin

---

README.md

Adding Video semantic plugin. To use fully, you will need a free account at https://twelvelabs.io/.

Adding Video Semantic Plugin by dan gural

---

plugins/examples/__init__.py
plugins/examples/fiftyone.yml

Add an example operator `lazy_field_example` for newly added operator view

add an example operator for LazyFieldView

---

plugins/brain/__init__.py
plugins/zoo/__init__.py

The `batch_size`/`num_workers`/`skip_failures` parameters were declared but never actually used in the `execute()` methods of several brain operators. This patches that 😅

Passing missing parameters to brain methods during execution

---

plugins/utils/__init__.py
plugins/zoo/__init__.py

Fix params for `open_dataset` triggers to pass `dataset` instead of `name`

fix params for open_dataset triggers

---

README.md

Adds an operator button to the sample modal to edit label attributes.
https://github.com/ehofesmann/edit_label_attributes/tree/main

Add label attribute editing plugin by Eric Hofesmann

---

plugins/io/__init__.py
plugins/utils/README.md
plugins/utils/__init__.py
plugins/utils/fiftyone.yml

- Adds a new `@voxel51/utils/delegate` operator that allows for programmatically [delegating execution](https://docs.voxel51.com/plugins/using_plugins.html#delegated-operations) of an arbitrary function call that can be expressed in any of the following forms:
-   Execute an arbitrary function: `fcn(*args, **kwargs)`
-   Apply a function to a dataset or view: `fcn(dataset_or_view, *args, **kwargs)`
-   Call an instance method of a dataset or view: `dataset_or_view.fcn(*args, **kwargs)`
- Adds some `__call__` implementations to common operators for which SDK-based execution is useful
- I thought about adding more `__call__` methods, but pretty much every remaining builtin `@voxel51/XXX` operation boils down to a single function call that can be accomplished via `@voxel51/utils/delegate` 💪 …

Callable plugins and delegated SDK execution 

---

plugins/annotation/__init__.py

Requesting annotations with current code, specifying a new label field and using the schema-builder to add classes results in error thrown from [here](https://github.com/voxel51/fiftyone/blob/4238a4bc95643d918f169aa180aaa6304f2db646/fiftyone/utils/annotations.py#L803)

Fix label schema for new label fields

---

plugins/io/__init__.py

Compared to the [documentation page](https://docs.voxel51.com/api/fiftyone.core.dataset.html?highlight=merge_samples#fiftyone.core.dataset.Dataset.merge_samples) the input fields' descriptions for "Insert new" and "Skip existing" where swapped in the UI of the plugin.

Fix wrong descriptions for "insert_new" & "skip_existing"

---

plugins/utils/README.md
plugins/utils/__init__.py
plugins/utils/fiftyone.yml

Adds a new `@voxel51/utils/apply_saved_view` operator:
You can use this operator to apply a saved view from another dataset to your
current dataset (assuming the view is applicable to both).
This operator is essentially a wrapper around the following code snippet:
```py
src_view = src_dataset.load_saved_view(name)
view = fo.DatasetView._build(dataset, src_view._serialize())
```
where the operator's form allows you to choose the source dataset and view to
apply.

Apply saved view

---

plugins/utils/__init__.py

Adds the `disable_frame_filtering` app config option introduced by https://github.com/voxel51/fiftyone/pull/4604 to the `@voxel51/utils/edit_dataset_info` operator.

Adding disable_frame_filtering option

---

plugins/plugins/__init__.py

The configs for Python operators have changed a bit since this was created. This PR introduces some minor tweaks to bring the interface up to date.
Still other changes to be made to the `@voxel51/plugins` plugin, including:
- Adding secrets declaration control to the `fiftyone.yml`. 
- Distinct code for when operator executes as generator, with yield... 
- Allow for multiple triggers, in arbitrary order, and using `ctx.ops` where possible
- Some reference to the docs or the `@voxel51/examples` plugin so people know other types exist, like `str`, `Tuple`, ..., which don't have multiple view type options, but still deserve to be included in this plugin
- if user has selected an icon file for one of the icons, then they should have the option to use this for another icon instead of going …

Operator skeleton upgrades

---

README.md

Hi, we've developed a plugin to integrate FiftyOne with our annotation tool ([Segments.ai](https://segments.ai))! Could this be added to the list of community plugins?

Added the Segments.ai integration plugin to the community plugin list

---

plugins/brain/__init__.py
plugins/brain/fiftyone.yml
plugins/zoo/__init__.py
plugins/zoo/fiftyone.yml

Backwards-compatible upgrade of the `@voxel51/zoo` plugin to support downloading [remotely-sourced zoo datasets](https://github.com/voxel51/fiftyone/pull/4752) and applying [remotely-sourced zoo models](https://github.com/voxel51/fiftyone/pull/4786).

Add support for remote zoo datasets/models

---

plugins/dashboard/__init__.py

**TEAMS ticket: [TEAMS-3641](https://voxel51.atlassian.net/browse/TEAMS-3641)**
- Clones FOTCS ticket [FOTCS-458](https://voxel51.atlassian.net/browse/FOTCS-458)
- Users should be allowed to choose `fo.DateField` and `fo.DateTimeField` fields when generating numeric histograms via the Dashboard panel.
- Need to include `DateField` and `DateTimeField` in `NUMERIC_TYPES` [here](https://github.com/voxel51/fiftyone-plugins/blob/b54d8340922333d7103eb20169897047e1de5001/plugins/dashboard/__init__.py#L35).  
- Confirmed that `get_number_field_choices` returns `DateTimeField` fields (quickstart’s `created_at` field as an example).  
- Though`view.histogram_values()` can handle these types and does return valid `counts` and `edges` running the plugin will result in `TypeError: Object of type …

Add the ability to plot datetime values as a numerical histogram in the Dashboard Panel

---

plugins/annotation/__init__.py
plugins/annotation/fiftyone.yml

This change makes it so that the available annotation backends in the `request_annotations` operator can be configured by setting the following secrets:
```
export FIFTYONE_ANNOTATION_BACKENDS=cvat,labelstudio
export FIFTYONE_ANNOTATION_DEFAULT_BACKEND=labelstudio
```

Allow configuring available annotation backends via secrets

---

plugins/dashboard/__init__.py

PR to add ability to plot DateTime data in dashboard panel did not contain `import datetime`, resulting in errors. This adds the line back to restore functionality.

Add missing import to dashboard panel

---

plugins/plugins/__init__.py
plugins/plugins/fiftyone.yml

Recent plugin framework changed how `default` values of read-only objects are handle in `ctx.params`, which broke the `@voxel51/plugins/manage_plugins` operator. This PR fixes that.

Avoid reliance on default values in ctx.params

---

plugins/operator-examples/README.md
plugins/operator-examples/__init__.py
plugins/operator-examples/fiftyone.yml

This example captures the best practices for creating Operators that support both delegated and immediate execution.
```python
ds = fo.load_dataset("quickstart")
complex_exec = foo.get_operator("@voxel51/operator-examples/example_complex_execution")
complex_exec(ds, message="hello")
```
```python
complex_exec(ds, message="hello", delegate=True)
```
> NOTE: this was run with `FIFTYONE_ALLOW_LEGACY_ORCHESTRATORS=true`
https://github.com/user-attachments/assets/68c457d0-8416-4d48-94eb-6fa8a5eb426f

Add best practice example for complex ops

---

plugins/evaluation/__init__.py

The previous implementation of `@voxel51/evaluation/evaluate_model` would automatically pick a default value for `iscrowd` if there were any suitably-typed fields on the objects. That was too aggressive as we have no idea what the fields actually contain.
It is better to require the user to pick a value from the dropdown if they want one.

Don't pick a crowd attribute by default when evaluating models

---

plugins/annotation/__init__.py
plugins/annotation/fiftyone.yml
plugins/brain/__init__.py
plugins/brain/fiftyone.yml
plugins/delegated/__init__.py
plugins/delegated/fiftyone.yml
plugins/evaluation/__init__.py
plugins/evaluation/fiftyone.yml
plugins/indexes/__init__.py
plugins/indexes/fiftyone.yml
plugins/io/__init__.py
plugins/io/fiftyone.yml
plugins/plugins/__init__.py
plugins/plugins/fiftyone.yml
plugins/plugins/utils.py
plugins/runs/__init__.py
plugins/runs/fiftyone.yml
plugins/utils/__init__.py
plugins/utils/fiftyone.yml
plugins/zoo/__init__.py
plugins/zoo/fiftyone.yml

As of `fiftyone==1.1.0`, the best practice is that all operators that allow delegated execution should implement this via their `OperatorConfig` (if static) or `resolve_execution_options()` (if dynamic), as the plugin framework itself is authoritative on whether delegated execution is allowed by the current environment.
This change is backwards compatible with older FO versions as well. The only implication is that `Schedule` will always be available to users running legacy FO versions in the `Execute|Schedule` button for operators that declare DO support, even if there is no orchestrator running to execute them.
Previously this footgun was still possible, but it was harded-coded into the operators themselves as shown below, which provided a proactive warning:
```py
def …
```

Use resolve_execution_options() to handle all delegated execution

---

plugins/annotation/__init__.py
plugins/annotation/fiftyone.yml

The `job_reviewers` parameter was [deprecated in CVAT v2](https://github.com/voxel51/fiftyone/blob/882055568b0fd6d83c4bcd01c5cc28eaceb16230/fiftyone/utils/cvat.py#L3070-L3071), so removing it from the plugin for user clarity.

Remove deprecated `job_reviewers` parameter from CVAT integration

---

plugins/io/__init__.py
plugins/plugins/__init__.py
plugins/utils/__init__.py
plugins/zoo/__init__.py

Uses `DropdownView` for all `list()` type fields, so that we can leverage the framework enhanced introduced by https://github.com/voxel51/fiftyone/pull/5375 in a backwards compatible way.
UX improvements with this PR when running the latest `fiftyone:develop`:
- The dropdown disappears after each selection
- The tag bubbles make it more clear that you're specifying multiple values
- The `x` action is convenient to clear existing choices
- Autocomplete is nice for folks that prefer type + ENTER style interaction

Use autocomplete dropdowns for all list fields

---

plugins/evaluation/__init__.py
plugins/metric-examples/__init__.py
plugins/metric-examples/fiftyone.yml

This PR adds absolute_error and mean_absolute_error metric operators (similar to [this](https://github.com/manushreegangwar/custom_metrics/blob/main/eval_metrics/__init__.py))
```py
import random
import numpy as np
dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()
for idx, sample in enumerate(dataset, 1):
ytrue = random.random() * idx
ypred = ytrue + np.random.randn() * np.sqrt(ytrue)
confidence = random.random()
sample["ground_truth"] = fo.Regression(value=ytrue)
sample["predictions"] = fo.Regression(value=ypred, confidence=confidence)
sample.save()
custom_metrics = {}
custom_metrics.update({"@voxel51/metric-examples/example_metric": dict(value="hello")})
custom_metrics.update({"@voxel51/metric-examples/absolute_error": …
```

Add absolute error and MAE as custom metrics

---

plugins/evaluation/__init__.py
plugins/metric-examples/__init__.py
plugins/metric-examples/fiftyone.yml

1. Make sure you are running the [`custom-metrics` branch](https://github.com/voxel51/fiftyone/pull/5279) of your `fiftyone` install
2. If you haven't already, install `fiftyone-plugins` in editable mode:
```shell
git clone https://github.com/voxel51/fiftyone-plugins
cd fiftyone-plugins
git checkout --track origin/custom-metrics
ln -s "$(pwd)" "$(fiftyone config plugins_dir)/fiftyone-plugins"
```
```py
dataset = foz.load_zoo_dataset("quickstart")
#
#
#
#
session = fo.launch_app(dataset)
#
#
metric = "@voxel51/metric-examples/example_metric"
kwargs = dict(value="spam")
results = dataset.evaluate_detections(
"predictions",
gt_field="ground_truth",
eval_key="eval",
custom_metrics={metric: kwargs},
) …
```

Add support for custom evaluation metrics

---

plugins/annotation/__init__.py
plugins/annotation/fiftyone.yml

This pr makes 2 additions to the annotaiton plugin
* It exposes the dest_field argument for all `load_annotations` calls
* It tweaks the CVAT support so that if you provide an existing project to upload annotations to, the classes and attributes remain empty so that the existing project schema is actually used (See note from CVAT integration docs: https://docs.voxel51.com/integrations/cvat.html#uploading-to-existing-projects)
Tested manually against a CVAT deployment. Created a project from an annotation run, uploaded a label field to that project in a new annotation run, loaded the annotations into a new destination field.

Annotation plugin updates

---

plugins/dashboard/__init__.py

Added in fixes for filter to get applied correctly + for the dashboard view to update correctly on clicking a datetime histogram bar
Earlier version would fail if there was a single datetime value for all samples in the datetime field, this PR also addresses that issue

Updates to fix callbacks for numeric histograms with datetime fields

---

plugins/zoo/__init__.py
plugins/zoo/fiftyone.yml

The `load_zoo_dataset` operator currently generates warnings like this:
```
Ignoring unsupported parameter 'tab' for importer type <class 'fiftyone.utils.data.importers.FiftyOneDatasetImporter'>
```
This fixes that by storing kwargs in a nested `ctx.params.kwargs` field rather than mixing them into the top-level `ctx.params` dict.
Tested by confirming that `load_zoo_dataset` can still successfully load datasets with (eg `coco-2017`) and without (eg `quickstart`) custom kwargs.

Prevent superfluous warnings in load_zoo_dataset operator

---

plugins/indexes/__init__.py
plugins/indexes/fiftyone.yml

The automatic null coercion behavior introduced by https://github.com/voxel51/fiftyone/pull/5375 in `fiftyone==1.3.0` broke the `manage_indexes` operator. This fixes that.

Fix null coercion bug with `manage_indexes` operator

---

plugins/delegated/__init__.py
plugins/delegated/fiftyone.yml

It appears that, at some point, the `default` parameter of `HiddenView` properties is no longer available in `execute()`, which breaks the `manage_delegated_operations` operator. This fixes that.

Fix missing `id` bug in `manage_delegated_operations` operator

---

plugins/brain/__init__.py
plugins/brain/fiftyone.yml

- Adds the `create_index` option to the `@voxel51/brain/compute_visualization` operator
- Adds a new `@voxel51/brain/manage_visualization_indexes` operator for adding/removing spatial indexes from existing visualizations

Add support for spatial indexes on visualization results

---

plugins/io/__init__.py

Resolves https://github.com/voxel51/fiftyone-plugins/issues/224.
https://github.com/voxel51/fiftyone/pull/5355 made a breaking change to `_add_samples_batch()`, so we can no longer call it in this plugin.
(we shouldn't have been calling private methods outside of the main `fiftyone` project anyways... 🙃)

Can no longer call `_add_samples_batch()` directly

---

plugins/dashboard/__init__.py

- Fixes plot selection callbacks for numeric histograms
- Fixes on-view-change plot reloading, which was accidentally broken in https://github.com/voxel51/fiftyone-plugins/pull/229/commits/691feeb399fe500a68335df9890bdf2599bc6c57
- Fixes scatter plot rendering for embedded list fields
- Optimizes plot data aggregations
Creating various chart types locally on `quickstart`:
```py
dataset = foz.load_zoo_dataset("quickstart")
dataset.compute_metadata()
session = fo.launch_app(dataset) 
```

Dashboard fixes/optimizations

---

plugins/evaluation/__init__.py

Fixing a copy-pasta error. The `missing` parameter is a float for regression tasks but is a string for classification and detection.

`missing` parameter is a string for classification/detection
