- packages/build/src/index.js
- packages/hello-world/src/HelloWorld.tsx
Adds build support for https://github.com/voxel51/fiftyone/pull/2680
> externalize plugin deps

- README.md
- plugins/evaluation/README.md
- plugins/evaluation/__init__.py
- plugins/evaluation/fiftyone.yml
Adds a plugin for evaluating models!
> Evaluation plugin

- plugins/examples/__init__.py
- plugins/examples/fiftyone.yml
An example showing various usage of `ctx.selected_labels`.
> selected labels example

- plugins/io/__init__.py
- plugins/io/fiftyone.yml
Change log
- Adds support for uploading images/labels from local machine via drop zones
- Adds additional import-only types
- Adds support for importing/exporting video types
- Adds support for exporting patches, clips, etc
- Adds support for label type coercions [as described here](https://docs.voxel51.com/user_guide/export_datasets.html#label-type-coercion)
> Upgrading I/O plugin

- README.md
A [FiftyOne plugin](https://docs.voxel51.com/plugins/index.html) for filtering
a field of your FiftyOne dataset by one or multiple values simultaneously. 
[filter_values.mp4](
https://github.com/ehofesmann/filter-values-plugin/assets/21222883/5195638b-add6-466b-944d-1bd6c51369a2)
If you haven't already,
[install FiftyOne](https://docs.voxel51.com/getting_started/install.html):
```shell
pip install fiftyone
```
Then install the plugin and its dependencies:
```shell
fiftyone plugins download https://github.com/ehofesmann/filter-values-plugin
```
1. Load your dataset (in this case the FiftyOne `quickstart` dataset), and
open the FiftyOne App:
```py
dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```
2. Select the …
> Add Filter Values operator

- README.md
Select one or multiple samples, and use GPT-4 Vision to answer questions about them!
> GPT-4 Vision Plugin

- README.md
> Add image anonymization plugin to the list

- plugins/examples/__init__.py
- plugins/examples/fiftyone.yml
Adding example operators for
- selected samples
- setting the view
- delegated execution
- secrets
> adding more example operators

- README.md
> Img to video

- README.md
Plugin has evolved to the point where it is more general and the name change is merited
> Rename AI art gallery plugin

- plugins/utils/__init__.py
Fix typo "clasess" -> "classes"
> Fix typo "clasess" -> "classes"

- README.md
Added the audio loader plugin. To test follow instructions in the Readme, make sure to have your audio in a classification tree directory structure
> Added audio_loader

- plugins/brain/__init__.py
Updates the `Visualization` import per https://github.com/voxel51/fiftyone-brain/pull/175
> Updating Visualization import per voxel51/fiftyone-brain#175

- plugins/plugins/__init__.py
componentProps --> componentsProps
> componentsProps Typo

- README.md
Adds outlier plugin to the table https://github.com/danielgural/outlier_detection
> Adding outlier to table

- README.md
Adds cluster plugin to the table https://github.com/danielgural/clustering_algorithms
> Adding cluster to the table

- README.md
Adds the plugin optimal confidence threshold https://github.com/danielgural/optimal_confidence_threshold
> Adding the confidence plugin to the table

- plugins/build/src/index.js
Required for https://github.com/voxel51/fiftyone/pull/4189
> build with fiftyone spaces package externalized

- plugins/runs/README.md
- plugins/runs/__init__.py
- plugins/runs/fiftyone.yml
Adds `@voxel51/runs` plugin, which wraps four SDK methods:
- `get_run_info()`
- `load_run_view()`
- `delete_run()`
- `rename_run()`
> Adds @voxel51/runs plugin

- plugins/indexes/README.md
- plugins/indexes/__init__.py
- plugins/indexes/fiftyone.yml
Updated the index management to keep track of size statistics
> Added size to index management plugin

- plugins/utils/README.md
- plugins/utils/__init__.py
- plugins/utils/fiftyone.yml
Adds a `@voxel51/utils/clone_dataset` operator
> Adding a clone_dataset operator

- README.md
See two additions to the community plugins list relating fiftyone-tile & fiftyone-timestamps as announced in #162
> Add fiftyone-tile & fiftyone-timestamps

- plugins/panel-examples/__init__.py
Supporting PR for https://github.com/voxel51/fiftyone/pull/4878
> Add video support to animated timeline

- plugins/zoo/__init__.py
> More helpful error messages when no models/datasets match all tags

- plugins/annotation/__init__.py
- plugins/brain/__init__.py
- plugins/dashboard/__init__.py
- plugins/delegated/__init__.py
- plugins/evaluation/__init__.py
- plugins/indexes/__init__.py
- plugins/io/__init__.py
- plugins/label_count/__init__.py
- plugins/operator-examples/__init__.py
- plugins/panel-examples/__init__.py
- plugins/plugins/__init__.py
- plugins/plugins/utils.py
- plugins/runs/__init__.py
- plugins/utils/__init__.py
- plugins/zoo/__init__.py
Updates copyright values
```sh
for file in $(ack -l "2017-2024"); do perl -pi -e 's/2017-2024/2017-2025/g' $file; done
```
> 2025 Copyright Updates

- README.md
Include multi-annotator-toolkit plugin to README.md
> Add community plugin to README.md

- plugins/dashboard/__init__.py
Resolves https://github.com/voxel51/fiftyone-plugins/issues/214
> Fix dashboard plots selection of data points to work from any view

- plugins/dashboard/fiftyone.yml
Bump the version of the dashboard plugin after recent bugfix.
> Bump dashboard version

- plugins/utils/__init__.py
Updates the `edit_dataset_info` changes added in https://github.com/voxel51/fiftyone-plugins/pull/209 to match https://github.com/voxel51/fiftyone/pull/5592, where `default_visibility_labels` was rebranded to `active_fields`.
> Replace `default_visibility_labels` with `active_fields`

- plugins/scenario/__init__.py
- plugins/scenario/utils.py
UX for custom code sample distribution graph
> Custom Code Preview Distribution

- plugins/io/__init__.py
Uses the new `add_samples(generator=True)` syntax introduced in https://github.com/voxel51/fiftyone/pull/5666 to regain the progress functionality in `@voxel51/io/import_samples` that we had to remove in https://github.com/voxel51/fiftyone-plugins/pull/226.
> Use `add_samples(generator=True)` syntax

- plugins/annotation/__init__.py
- plugins/brain/__init__.py
- plugins/io/__init__.py
- plugins/utils/__init__.py
- plugins/zoo/__init__.py
Ensures that all core plugins support fields embedded in dynamic documents, just like we did for `@voxel51/evaluation` in https://github.com/voxel51/fiftyone-plugins/pull/216.
Side note: I got annoyed at the amount of code required to support this, so I added a new syntax to `get_field_schema()` in https://github.com/voxel51/fiftyone/pull/5663 that will allow us to delete these `_get_sample_fields()` and `_get_label_fields()` methods (but I didn't actually do it yet so that these plugins remain backwards compatible...)
> Support embedded fields in all core plugins

- plugins/dashboard/__init__.py
- plugins/dashboard/fiftyone.yml
- Added `@execution_cache` decorator to the Dashboard panel to optimize plot previews
> Add `@execution_cache` to dashboard panel to optimize plot previews

- plugins/utils/__init__.py
Copy update to match https://github.com/voxel51/fiftyone/pull/5955.
> Explain that indexes are not included when cloning `dataset.view()`

- README.md
This PR adds the **FiftyOne VLM Efficient** plugin, a toolkit for improving training data quality in Vision-Language Models (VLMs) using research-backed techniques.
* 🔍 **SIEVE method** for multimodal dataset pruning
* 📚 Based on [SIEVE: Multimodal Dataset Pruning Using Image Captioning Models (CVPR 2024)](https://openaccess.thecvf.com/content/CVPR2024/papers/Mahmoud_Sieve_Multimodal_Dataset_Pruning_using_Image_Captioning_Models_CVPR_2024_paper.pdf)
* 🛠️ Future support planned for FitPrune, VILA, LLaVA, and other techniques
This plugin provides a fast, accessible way to curate high-quality VLM datasets directly within the FiftyOne App.
> Integrate VLM Efficient plugin for lightweight zero-shot object detection

- plugins/dashboard/README.md
Document an advanced way to query multiple datasets.
> Add adv dashboard docs
